version: '1.0'
createdAt: '2025-12-05T17:53:15.184Z'
settings:
  showDockEdit: true
  showSearchBar: true
  showPagination: true
  showDock: true
wallpaper: https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop
shortcuts:
  - id: baidu
    title: 百度搜索
    url: https://www.baidu.com
    type: auto
    color: from-blue-500 to-blue-600
  - id: translate
    title: 谷歌翻译
    url: https://translate.google.cn
    type: auto
    color: from-blue-400 to-blue-500
  - id: chatgpt
    title: ChatGPT
    url: https://chat.openai.com
    type: chatgpt
    color: from-emerald-500 to-teal-600
    isApp: true
  - id: weibo
    title: 微博热搜
    url: https://weibo.com
    type: auto
    color: from-yellow-400 to-red-500
  - id: zhihu
    title: 知乎
    url: https://www.zhihu.com
    type: auto
    color: from-blue-600 to-blue-700
  - id: mail
    title: 163邮箱
    url: https://mail.163.com
    type: auto
    color: from-green-500 to-emerald-600
  - id: weather
    title: 墨迹天气
    url: https://www.moji.com
    type: auto
    color: from-sky-400 to-blue-400
  - title: Clock
    type: widget
    widgetType: clock
    widgetContent: ''
    size:
      w: 1
      h: 1
    color: from-white to-gray-100
    id: widget-clock
  - id: taobao
    title: 淘宝
    url: https://www.taobao.com
    type: auto
    color: from-orange-500 to-orange-600
  - id: jd
    title: 京东
    url: https://www.jd.com
    type: auto
    color: from-red-600 to-red-700
  - id: meituan
    title: 美团外卖
    url: https://www.meituan.com
    type: auto
    color: from-yellow-400 to-yellow-500
  - id: xiachufang
    title: 下厨房
    url: https://www.xiachufang.com
    type: auto
    color: from-red-400 to-red-500
  - id: amap
    title: 高德地图
    url: https://www.amap.com
    type: auto
    color: from-blue-500 to-cyan-500
  - id: 12306
    title: 铁路12306
    url: https://www.12306.cn
    type: auto
    color: from-blue-700 to-blue-900
  - id: pan
    title: 阿里云盘
    url: https://www.aliyundrive.com
    type: auto
    color: from-indigo-500 to-purple-600
  - id: xianyu
    title: 闲鱼
    url: https://2.taobao.com
    type: auto
    color: from-yellow-300 to-yellow-400
  - id: bili
    title: Bilibili
    url: https://www.bilibili.com
    type: bilibili
    color: from-pink-400 to-pink-500
  - id: douyin
    title: 抖音
    url: https://www.douyin.com
    type: auto
    color: from-gray-900 to-black
  - id: netease
    title: 网易云音乐
    url: https://music.163.com
    type: auto
    color: from-red-600 to-red-700
  - id: douban
    title: 豆瓣书影音
    url: https://www.douban.com
    type: auto
    color: from-green-600 to-green-700
  - title: Calendar
    type: widget
    widgetType: calendar
    widgetContent: ''
    size:
      w: 2
      h: 2
    color: from-white to-gray-100
    id: widget-calendar
  - id: github
    title: GitHub
    url: https://github.com
    type: github
    color: from-gray-800 to-black
  - id: csdn
    title: CSDN
    url: https://www.csdn.net
    type: auto
    color: from-red-600 to-red-700
  - id: gitee
    title: Gitee
    url: https://gitee.com
    type: auto
    color: from-red-700 to-red-800
  - id: juejin
    title: 掘金
    url: https://juejin.cn
    type: auto
    color: from-blue-500 to-blue-600
  - id: linuxdo
    title: Linux.do
    url: https://linux.do
    type: auto
    color: from-gray-700 to-gray-800
  - id: figma
    title: Figma
    url: https://figma.com
    type: auto
    color: from-purple-500 to-rose-500
dockItems:
  - id: ai
    iconType: cpu
    name: AI 助手
    isApp: true
    type: sys
    color: from-purple-500 to-indigo-500
  - id: notes
    iconType: sticky-note
    name: 随手记
    isApp: true
    type: sys
    color: from-yellow-400 to-orange-400
  - id: calc
    iconType: calculator
    name: 计算器
    isApp: true
    type: sys
    color: from-gray-500 to-gray-600
  - id: wechat
    title: 微信
    url: https://wx.qq.com
    type: auto
    color: from-green-500 to-green-600
    iconType: message-circle
    size:
      w: 1
      h: 1
  - id: settings
    iconType: settings
    name: 系统设置
    isApp: true
    type: sys
    color: from-slate-500 to-slate-600
